# Generated by Django 4.0.4 on 2022-05-13 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainWebsite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
