# Generated by Django 4.0.4 on 2022-05-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MainWebsite', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Publisher', models.CharField(default=' ', max_length=100)),
                ('PublishDate', models.DateField(auto_now_add=True)),
                ('Content', models.TextField(blank=True, default=' ')),
            ],
        ),
    ]
