# Generated by Django 4.0.4 on 2022-05-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWebsite', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Publisher', models.CharField(default=' ', max_length=100)),
                ('PublishDate', models.DateField(auto_now_add=True)),
                ('Content', models.TextField(blank=True, default=' ')),
                ('Image', models.ImageField(blank=True, upload_to='PostImages')),
            ],
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
