# Generated by Django 4.0.4 on 2022-05-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWebsite', '0004_post_delete_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailedUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default=' ', max_length=100)),
                ('gender', models.CharField(default='male', max_length=10)),
                ('status', models.CharField(default='online', max_length=10)),
                ('friends', models.JSONField(null=True)),
                ('image', models.ImageField(default='/UserProfilePics/default.jpg', upload_to='UserProfilePics')),
                ('fname', models.CharField(max_length=100, null=True)),
                ('lname', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
