# Generated by Django 4.0.4 on 2022-05-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWebsite', '0005_detaileduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Comments',
            field=models.JSONField(default=list),
        ),
    ]
