# Generated by Django 4.0.4 on 2022-05-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWebsite', '0006_post_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='PublisherImage',
            field=models.ImageField(blank=True, upload_to='PostImages'),
        ),
    ]
