# Generated by Django 4.0.4 on 2022-05-16 05:50

import MainWebsite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWebsite', '0010_alter_post_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detaileduser',
            name='friends',
            field=models.JSONField(default=MainWebsite.models.defaultJsonValue),
        ),
    ]
