# Generated by Django 4.0.4 on 2022-05-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWebsite', '0011_alter_detaileduser_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detaileduser',
            name='fname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detaileduser',
            name='lname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
