# Generated by Django 4.0.4 on 2022-05-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWebsite', '0012_alter_detaileduser_fname_alter_detaileduser_lname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detaileduser',
            name='fname',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='detaileduser',
            name='lname',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
