# Generated by Django 4.0.4 on 2022-05-18 05:53

import MainWebsite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWebsite', '0014_alter_detaileduser_fname_alter_detaileduser_lname'),
    ]

    operations = [
        migrations.AddField(
            model_name='detaileduser',
            name='chats',
            field=models.JSONField(default=MainWebsite.models.defaultJsonValue),
        ),
    ]
