# Generated by Django 4.0.4 on 2022-05-19 09:46

import MainWebsite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWebsite', '0017_alter_detaileduser_chats'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Likers',
            field=models.JSONField(default=MainWebsite.models.defaultJsonValue),
        ),
    ]
